### ISSUE TITLE
MenuAtom 누를때 url이 망가짐

### ISSUE THREAD

**Issue by akdlsz21** [KangHayeonn/Too-Good-To-Go#32]
![MenuAtom](https://user-images.githubusercontent.com/81629070/140321699-5344d0a7-cf9d-4aeb-b60e-ae1f1bf99803.png)

ShopHeaderMenu 중 하나를 클릭할때 href이 점점 중복적으로 추가됨. 

![hrefBroken](https://user-images.githubusercontent.com/81629070/140321793-81d8e11a-b715-444e-9558-d9e92348dcba.png)

**Comment by ksone02** [comment]
인지하고 있었고, 추후 수정하려고 했습니다... 지적 감사합니다 ㅋㅋ 수정할게요
